/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/rankings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rankings */
        get: operations["get_rankings_api_rankings__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ticker/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticker */
        get: operations["get_ticker_api_ticker__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio */
        get: operations["get_portfolio_api_portfolio__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/buy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Buy Stock */
        post: operations["buy_stock_api_portfolio_buy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/sell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sell Stock */
        post: operations["sell_stock_api_portfolio_sell_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Backtest */
        post: operations["run_backtest_api_backtest__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Prices */
        get: operations["stream_prices_api_stream_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sectors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sectors */
        get: operations["get_sectors_api_sectors__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News */
        get: operations["get_news_api_news__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestRequest */
        BacktestRequest: {
            /**
             * Initial Capital
             * @default 100000
             */
            initial_capital: number;
            /**
             * Months
             * @default 6
             */
            months: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NewsItem */
        NewsItem: {
            /** Title */
            title: string;
            /** Publisher */
            publisher: string;
            /** Link */
            link: string;
            /** Providerpublishtime */
            providerPublishTime: number;
            /** Relatedtickers */
            relatedTickers: string[];
        };
        /** PortfolioActionRequest */
        PortfolioActionRequest: {
            /** Ticker */
            ticker: string;
            /** Price */
            price: number;
            /** Shares */
            shares: number;
            /**
             * Score
             * @default 0
             */
            score: number;
        };
        /** PortfolioSellRequest */
        PortfolioSellRequest: {
            /** Trade Id */
            trade_id: number;
            /** Exit Price */
            exit_price: number;
        };
        /** RankingSchema */
        RankingSchema: {
            /** Ticker */
            ticker: string;
            /** Conviction Score */
            conviction_score: number;
            /** Consensus Ratio */
            consensus_ratio: number;
            /** Implied Upside Pct */
            implied_upside_pct: string;
            /** Analyst Rating */
            analyst_rating: number;
            /** Trend */
            trend: string;
            /** News Risk */
            news_risk: string;
            /** Score Breakdown */
            score_breakdown: {
                [key: string]: number;
            };
            raw_data: components["schemas"]["TickerInfoSchema"];
            /**
             * Last Updated
             * Format: date-time
             */
            last_updated: string;
        };
        /** SectorSchema */
        SectorSchema: {
            /** Sector */
            sector: string;
            /** Avg Score */
            avg_score: number;
            /** Ticker Count */
            ticker_count: number;
        };
        /** TickerInfoSchema */
        TickerInfoSchema: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /**
             * Sector
             * @default Unknown
             */
            sector: string;
            /**
             * Industry
             * @default Unknown
             */
            industry: string;
            /** Current Price */
            current_price: number;
            /**
             * Target Mean
             * @default 0
             */
            target_mean: number;
            /** Peg Ratio */
            peg_ratio?: number | null;
            /** Beta */
            beta?: number | null;
            /**
             * Strong Buy
             * @default 0
             */
            strong_buy: number;
            /**
             * Buy
             * @default 0
             */
            buy: number;
            /**
             * Hold
             * @default 0
             */
            hold: number;
            /**
             * Sell
             * @default 0
             */
            sell: number;
            /**
             * Strong Sell
             * @default 0
             */
            strong_sell: number;
            /**
             * Total Analysts
             * @default 0
             */
            total_analysts: number;
            /** Rsi */
            rsi?: number | null;
            /** Sma 50 */
            sma_50?: number | null;
            /** Sma 200 */
            sma_200?: number | null;
            /**
             * Avg Sentiment
             * @default 0
             */
            avg_sentiment: number;
        };
        /** TradeRecordSchema */
        TradeRecordSchema: {
            /** Id */
            id?: number | null;
            /** Ticker */
            ticker: string;
            /** Entry Price */
            entry_price: number;
            /** Shares */
            shares: number;
            /**
             * Entry Date
             * Format: date-time
             */
            entry_date: string;
            /** Entry Score */
            entry_score: number;
            /** Status */
            status: string;
            /** Exit Price */
            exit_price?: number | null;
            /** Exit Date */
            exit_date?: string | null;
            /** Profit Loss */
            profit_loss?: number | null;
            /** Profit Loss Pct */
            profit_loss_pct?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_rankings_api_rankings__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingSchema"][];
                };
            };
        };
    };
    get_ticker_api_ticker__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerInfoSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_api_portfolio__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeRecordSchema"][];
                };
            };
        };
    };
    buy_stock_api_portfolio_buy_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sell_stock_api_portfolio_sell_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioSellRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_backtest_api_backtest__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_prices_api_stream_prices_get: {
        parameters: {
            query: {
                /** @description Comma-separated list of symbols */
                symbols: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sectors_api_sectors__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorSchema"][];
                };
            };
        };
    };
    get_news_api_news__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
